services:
  nats_server:
    image: nats:latest
    container_name: "nats_server"
    environment:
      - NATS_SERVER_NAME=nats-server
    command:
      -js
    volumes:
      - ./nats_server_data:/data
      - ./nats/config:/config
    ports:
      - "${NATS_PORT_4}:4222"
      - "${NATS_PORT_6}:6222"
      - "${NATS_PORT_8}:8222"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - xcvzv97opksje
    restart: always


volumes:
  nats_server_data:
    driver: local


networks:
  xcvzv97opksje:
    external: true
